spring.application.name=gst-billing
# SERVER PORT
# Render strictly requires apps to listen to the PORT environment variable!
server.port=${PORT:8080}

# DATABASE (Neon connection via Render variables)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/inventory_gst_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}

# HIBERNATE
# 'update' is fine for a portfolio project so Neon auto-builds the tables.
# In a real company, this is strictly 'validate' or 'none'.
spring.jpa.hibernate.ddl-auto=update

# SECURITY
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# will show sql queries in console so can easily see
spring.jpa.show-sql=true

razorpay.key.id=${RZP_KEY_ID}
razorpay.key.secret=${RZP_KEY_SECRET}

# to see error message in postman as well not just console
server.error.include-message=always
